# Generated by Django 4.0.2 on 2024-04-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='start_date',
        ),
    ]
